#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=659027890482
BundleId=com.byrese.ganbaresuperstrikers
ClientId=659027890482-bepipu6m8mk72l0t6nbrv7j6hb6u0usd.apps.googleusercontent.com

*/

#define kAppID "659027890482"
#define kBundleID "com.byrese.ganbaresuperstrikers"
#define kClientID "659027890482-bepipu6m8mk72l0t6nbrv7j6hb6u0usd.apps.googleusercontent.com"

#endif


